/* Generated by solo5-elftool version v0.12.0, do not edit */

#define MFT_ENTRIES 1
#include "mft_abi.h"

MFT1_NOTE_DECLARE_BEGIN
{
  .version = MFT_VERSION, .entries = 1,
  .e = {
    { .name = "", .type = MFT_RESERVED_FIRST },
  }
}
MFT1_NOTE_DECLARE_END
